easy_admin:

    entities:

        Media:
            class: App\Entity\Media
            label: 'Media'
            list:
                title: '%%entity_label%% listing'
                fields: ['id', 'filename', 'flacExists', 'transcriptRequested', 'wordCount', 'sentenceCount', 'fileSize']
