easy_admin:
    formats:
        # ...
        # number: '%.2f'

    design:
        menu:
            - {route: 'survos_landing', label: 'Home' }
            - {entity: Media}
            - {entity: Project}
            - {entity: Marker }
            - {entity: Broll }
            - {entity: Word }
            - {entity: User }
            - { label: 'Workflow', icon: code-fork, route: 'survos_workflows' }

    entities:
        Broll:
            class: App\Entity\BRoll

        User:
            class: App\Entity\User
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - 'id'
                    - { property: 'email', type: 'email' }
                    # - { property: 'roles' }
                    # - { property: 'roles', type_options: { expanded: true, multiple: true } }
                # ...
            list:
                fields:
                - username
                - email
                - roles




        Media:
            class: App\Entity\Media
            label: 'Media'
            list:
                title: '%%entity_label%% listing'
                fields:
                - 'id'
                - type
                - code
                - 'filename'
                - path
                - streamCount
                - height
                - width
                - frameDuration
                - {property: 'transcriptRequested', label: 'Transcribe?'}
                - {property: 'flacExists', label: 'Flac?'}
                - project
                - words
                - 'duration'
                - sentenceCount
                - {property: 'fileSize', type: 'float', format: '%3.1f'}
                - 'transcribeSize'
                actions: ['show', { name: 'media_show', type: 'route' }, 'delete', 'edit']

        Marker:
            class: App\Entity\Marker

        Word:
            class: App\Entity\Word

        Project:
            class: App\Entity\Project
            label: 'Bin'


