easy_admin:
    formats:
        # ...
        number: '%.2f'

    entities:

        Media:
            class: App\Entity\Media
            label: 'Media'
            list:
                title: '%%entity_label%% listing'
                fields: ['id', 'filename', 'transcriptRequested', 'wordCount', 'sentenceCount', {property: 'fileSize', type: 'float', format: '%3.1f'} ]
                actions: ['show', { name: 'media_show', type: 'route' }, 'delete', 'edit']