easy_admin:
    formats:
        # ...
        # number: '%.2f'

    design:
        menu:
            - {route: 'survos_landing', label: 'Home' }
            - {entity: Media}
            - {entity: Project}
            - {entity: Marker }
            - {entity: Word }
            - { label: 'Workflow', icon: code-fork, route: 'survos_workflows' }

    entities:

        Marker:
            class: App\Entity\Marker

        Word:
            class: App\Entity\Word

        Project:
            class: App\Entity\Project
            label: 'Bin'


        Media:
            class: App\Entity\Media
            label: 'Media'
            list:
                title: '%%entity_label%% listing'
                fields:
                    - 'id'
                    - code
                    - 'filename'
                    - path
                    - streamCount
                    - {property: 'transcriptRequested', label: 'Transcribe?'}
                    - {property: 'flacExists', label: 'Flac?'}
                    - project
                    - words
                    - 'duration'
                    - sentenceCount
                    - {property: 'fileSize', type: 'float', format: '%3.1f'}
                    - 'transcribeSize'
                actions: ['show', { name: 'media_show', type: 'route' }, 'delete', 'edit']
