<?php

// generated by App\Services\MltService
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProfileRepository")
 */
class Profile
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }
    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     * @SerializedName("@name")
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     * @SerializedName("@colorspace")
     */
    private $colorspace;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     * @SerializedName("@description")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     * @SerializedName("@display_aspect_den")
     */
    private $display_aspect_den;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     * @SerializedName("@display_aspect_num")
     */
    private $display_aspect_num;

    /**
     * @ORM\Column(type="string", length=32, nullable=false)
     * @SerializedName("@frame_rate_den")
     */
    private $frame_rate_den;

    /**
     * @ORM\Column(type="string", length=32, nullable=false)
     * @SerializedName("@frame_rate_num")
     */
    private $frame_rate_num;

    /**
     * @ORM\Column(type="string", length=32, nullable=false)
     * @SerializedName("@height")
     */
    private $height;

    /**
     * @ORM\Column(type="string", length=32, nullable=false)
     * @SerializedName("@progressive")
     */
    private $progressive;

    /**
     * @ORM\Column(type="string", length=32, nullable=false)
     * @SerializedName("@sample_aspect_den")
     */
    private $sample_aspect_den;

    /**
     * @ORM\Column(type="string", length=32, nullable=false)
     * @SerializedName("@sample_aspect_num")
     */
    private $sample_aspect_num;

    /**
     * @ORM\Column(type="string", length=32, nullable=false)
     * @SerializedName("@width")
     */
    private $width;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $test;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $test2;

    public function getTest(): ?string
    {
        return $this->test;
    }

    public function setTest(string $test): self
    {
        $this->test = $test;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getColorspace(): ?string
    {
        return $this->colorspace;
    }

    public function setColorspace(?string $colorspace): self
    {
        $this->colorspace = $colorspace;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDisplayAspectDen(): ?string
    {
        return $this->display_aspect_den;
    }

    public function setDisplayAspectDen(?string $display_aspect_den): self
    {
        $this->display_aspect_den = $display_aspect_den;

        return $this;
    }

    public function getDisplayAspectNum(): ?string
    {
        return $this->display_aspect_num;
    }

    public function setDisplayAspectNum(?string $display_aspect_num): self
    {
        $this->display_aspect_num = $display_aspect_num;

        return $this;
    }

    public function getFrameRateDen(): ?string
    {
        return $this->frame_rate_den;
    }

    public function setFrameRateDen(string $frame_rate_den): self
    {
        $this->frame_rate_den = $frame_rate_den;

        return $this;
    }

    public function getFrameRateNum(): ?string
    {
        return $this->frame_rate_num;
    }

    public function setFrameRateNum(string $frame_rate_num): self
    {
        $this->frame_rate_num = $frame_rate_num;

        return $this;
    }

    public function getHeight(): ?string
    {
        return $this->height;
    }

    public function setHeight(string $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getProgressive(): ?string
    {
        return $this->progressive;
    }

    public function setProgressive(string $progressive): self
    {
        $this->progressive = $progressive;

        return $this;
    }

    public function getSampleAspectDen(): ?string
    {
        return $this->sample_aspect_den;
    }

    public function setSampleAspectDen(string $sample_aspect_den): self
    {
        $this->sample_aspect_den = $sample_aspect_den;

        return $this;
    }

    public function getSampleAspectNum(): ?string
    {
        return $this->sample_aspect_num;
    }

    public function setSampleAspectNum(string $sample_aspect_num): self
    {
        $this->sample_aspect_num = $sample_aspect_num;

        return $this;
    }

    public function getWidth(): ?string
    {
        return $this->width;
    }

    public function setWidth(string $width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getTest2(): ?string
    {
        return $this->test2;
    }

    public function setTest2(string $test2): self
    {
        $this->test2 = $test2;

        return $this;
    }

}