<?php

namespace App\Services;

use Soothsilver\DtdParser\Element;
use Symfony\Component\Serializer\Annotation\SerializedName;
use Soothsilver\DtdParser\Dtd\Parser;

class MltService
{

    /**
     * Load the DTD and generate Entity classes with the appropriate @SerializedName()
     */
    public function generateClasses()
    {
        $dtdText = file_get_contents(__DIR__ . '/../../mlt-xml.dtd');
        $dtd = \Soothsilver\DtdParser\DTD::parseText($dtdText);

        foreach ($dtd->elements as $code => $element) {
            $shortName = ucfirst($code);
            $class = 'App\\Entity\\' . ucfirst($code);
            $file = __DIR__ . sprintf('/../Entity/%s.php', $shortName);
            if (!file_exists($file)) {
                dd("bin/console make:entity $shortName");
            }
            $php = file_get_contents($file);

            $newProperties = $this->getPhpCode($element);

            //

            // inject the new property
            dd($newProperties);
            dd($code, $element);
        }

    }

    private function getPhpCode($element)
    {
        $code = ['Generated by ' . __CLASS__];

        $template = <<< REGEXP
    /**
     * @ORM\Column(type="string", length=32, nullable=%s)
     * @SerializedName("@%s")
     */
    private $%s;

REGEXP;

        /** @var \Soothsilver\DtdParser\Dtd\Element */
        foreach ($element->attributes as $name=>$attribute) {
            $block = sprintf($template,  $attribute->defaultType === '#REQUIRED' ? 'false' : 'true', $name, $name);
            array_push($code, $block);
        }
        /**  */

    return join("\n", $code);
    }

}